baseurl = "https://me.hamster.de/"
languageCode = "de-de"
title = "About HaMster"

theme = "hugo-uno"

[Params]
  AuthorName = "Hans Meyer"
  github = "HaMster21"
  twitter = "HaMster33460"
  email = "hans.meyer@mailbox.org"
  description = "Nerd, Vater, Teetrinker"
  cv = "/pages/cv"
